version: '3.9'

services:
  mysql:
    image: postgres:14.5
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/data/app/init.sql
    command: --init-file /data/app/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=top-secret
      - MYSQL_PASSWORD=so-secret
      - MYSQL_USER=lucas111
      - MYSQL_DATABASE=lucas-db
